# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dashboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dashboard
#    pod 'Alamofire'
#    pod 'MBProgressHUD'
#    pod 'IQKeyboardManagerSwift', '6.5.0'
#    pod 'Kingfisher', '~> 5.0'
    pod 'SideMenu'
    pod 'Charts'

  target 'DashboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DashboardUITests' do
    # Pods for testing
  end

end
